### ISSUE TITLE
How long did the training took? 

### ISSUE THREAD

**Issue by dame-cell** [whyNLP/tinyllama-zh#1]
How long did it take to train the entire model ??

**Comment by why-in-Shanghaitech** [comment]
Hi! As described in the readme, the training takes approximately 6 days (precisely 5d 23.2h) on 8 A100 GPUs, including the validation process. The details can be found on [wandb](https://api.wandb.ai/links/whynlp/zlszoc17).

**Comment by ddkwork** [comment]
可以让ollama加载这个模型进行中英互译嘛？

**Comment by why-in-Shanghaitech** [comment]
> 可以让ollama加载这个模型进行中英互译嘛？

你好！我不建议您使用这个模型来做中英互译，因为：
1. 这只是一个在中文语料上训练的示例模型。由于完全替换了词表，它不再具备原始TinyLlama的英文能力。一些测试显示这个模型的英文能力较弱；
2. 示例模型并未进行指令微调，因此可能难以遵循指令完成任务。

对于用ollama加载模型，由于我不是ollama的用户，所以对使用ollama加载模型不是很熟悉，这也许可以通过转换模型格式来完成，如：https://www.markhneedham.com/blog/2023/10/18/ollama-hugging-face-gguf-models/
但由于没有做指令微调，即使成功加载，您也无法通过对话的方式使用这个模型。

**Comment by ddkwork** [comment]
凹



---Original---
From: "Haoyi ***@***.***&gt;
Date: Sun, Mar 24, 2024 12:24 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [whyNLP/tinyllama-zh] How long did the training took?  (Issue #1)




  
可以让ollama加载这个模型进行中英互译嘛？
  
你好！我不建议您使用这个模型来做中英互译，因为：
  
这只是一个在中文语料上训练的示例模型。由于完全替换了词表，它不再具备原始TinyLlama的英文能力。一些测试显示这个模型的英文能力较弱；
 
示例模型并未进行指令微调，因此可能难以遵循指令完成任务。
  
对于用ollama加载模型，由于我不是ollama的用户，所以对使用ollama加载模型不是很熟悉，这也许可以通过转换模型格式来完成，如：https://www.markhneedham.com/blog/2023/10/18/ollama-hugging-face-gguf-models/
 但由于没有做指令微调，即使成功加载，您也无法通过对话的方式使用这个模型。

**Comment by dame-cell** [comment]
> Hi! As described in the readme, the training takes approximately 6 days (precisely 5d 23.2h) on 8 A100 GPUs, including the validation process. The details can be found on [wandb](https://api.wandb.ai/links/whynlp/zlszoc17).

Thanks , I'm trying to do the same but on only like 1 billion token on a single A10G GPU and wanted a rough estimate of how long it would take , this helped me a lot

**Comment by why-in-Shanghaitech** [comment]
Thank you for your reply! Since the issue has been resolved, I'm closing this issue. Feel free to reopen it if you run into any other problems.
